# API server listen address
# Defauls to: ":8080" which will listen on all avalable interfaces.
# Overwrite with environment variable: DEVICECONFIG_LISTEN
listen: :8080

# Mongodb connection string
# Defaults to: "mongodb://mender-mongo:27017"
# Overwrite with environment variable: DEVICECONFIG_MONGO_URL
mongo_url: mongodb://mender-mongo:27017

# Mongodb database name
# Defaults to: "deviceconfig"
# Overwrite with environment variable: DEVICECONFIG_MONGO_DBNAME
mongo_dbname: deviceconfig

# Enable SSL for mongo connections
# Defaults to: false
# Overwrite with environment variable: DEVICECONFIG_MONGO_SSL
mongo_ssl: false

# SkipVerify controls whether a mongo client verifies the
# server's certificate chain and host name.
# If InsecureSkipVerify is true, accepts any certificate
# presented by the server and any host name in that certificate.
# Defaults to: false
# Overwrite with environment variable: DEVICECONFIG_MONGO_SSL_SKIPVERIFY
mongo_ssl_skipverify: false

# Mongodb username
# Overwrites username set in connection string.
# Defaults to: none
# Overwrite with environment variable: DEVICECONFIG_MONGO_USERNAME
mongo_username: ""

# Mongodb password
# Overwrites password set in connection string.
# Defaults to: none
# Overwrite with environment variable: DEVICECONFIG_MONGO_PASSWORD
mongo_password: ""

## workflows service URL
## Defaults to: "http://mender-workflows:8080"
## Overwrite with environment variable DEVICECONFIG_WORKFLOWS_URL
workflows_url: http://mender-workflows:8080

# Enable audit logging
# Defaults to: false (disabled)
# Overwrite with environment variable: DEVICECONFIG_ENABLE_AUDIT
enable_audit: false
